version: '3'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zaq1
    volumes:
      - db:/var/lib/mysql/
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=zaq1
    ports:
      - 8081:80
    depends_on:
      - db

  phpapp:
    image: siqek/phpmysqli:1.0
    container_name: php
    volumes:
      - ./:/var/www/html/
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db: